website/phonebook/urls.py
from django.urls import re_path
from . import views

app_name = 'phonebook'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^search/(?P<data>.*)$', views.SearchView.as_view(), name='search'),
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='person_detail'),
    re_path(r'^person/add/$', views.PersonCreate.as_view(), name='add_person'),
    re_path(r'^person/(?P<pk>[0-9]+)/$', views.PersonUpdate.as_view(), name='update_person'),
    re_path(r'^person/(?P<pk>[0-9]+)/delete/$', views.PersonDelete.as_view(), name='delete_person'),
    re_path(r'^(?P<pk>[0-9]+)/addphone/$', views.PhoneCreate.as_view(), name='add_phone'),
    re_path(r'^phone/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', views.PhoneUpdate.as_view(), name='update_phone'),
    re_path(r'^phone/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/delete/$', views.PhoneDelete.as_view(), name='delete_phone'),
    re_path(r'^(?P<pk>[0-9]+)/addemail/$', views.EmailCreate.as_view(), name='add_email'),
    re_path(r'^email/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', views.EmailUpdate.as_view(), name='update_email'),
    re_path(r'^email/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/delete/$', views.EmailDelete.as_view(), name='delete_email'),
]

website/website/urls.py
#from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('phonebook/', include('phonebook.urls')),
]

website/phonebook/models.py
from django.db import models
from django.urls import reverse


class Person(models.Model):
    firstName = models.CharField(max_length=50, verbose_name="Imię")
    lastName = models.CharField(max_length=50, verbose_name="Nazwisko")

    class Meta:
        unique_together = [['firstName', 'lastName']]

    def get_absolute_url(self):
        return reverse('phonebook:person_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.firstName + ' ' + self.lastName


class PhoneNumber(models.Model):
    person = models.ForeignKey(Person, on_delete=models.PROTECT, editable=False)
    number = models.CharField(max_length=50, verbose_name="Numer telefonu")

    def get_absolute_url(self):
        return reverse('phonebook:person_detail', kwargs={'pk': self.person.pk})

    def __str__(self):
        return self.number


class Email(models.Model):
    person = models.ForeignKey(Person, on_delete=models.PROTECT, editable=False)
    email = models.EmailField()

    def get_absolute_url(self):
        return reverse('phonebook:person_detail', kwargs={'pk': self.person.pk})

    def __str__(self):
        return self.email

website/phonebook/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Person, PhoneNumber, Email
from django.db.models import ProtectedError
from django.contrib import messages
from django.http import HttpResponseRedirect
from itertools import chain
from django.db.models import Q


class IndexView(generic.ListView):
    template_name = 'phonebook/index.html'
    context_object_name = 'all_people'
    paginate_by = 10

    def get_queryset(self):
        return Person.objects.order_by('lastName')

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(IndexView, self).post(self, request, *args, **kwargs)


class SearchView(generic.ListView):
    template_name = 'phonebook/searched.html'
    context_object_name = 'all_people'
    paginate_by = 10

    def get_queryset(self):
        data = self.kwargs['data']
        all_people = Person.objects.filter(Q(firstName__contains=data) | Q(lastName__contains=data))
        all_numbers = PhoneNumber.objects.filter(number__contains=data)
        all_email = Email.objects.filter(email__contains=data)
        if all_numbers:
            all_people = chain(all_people, all_numbers)
        if all_email:
            all_people = chain(all_people, all_email)
        return list(all_people)

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(SearchView, self).post(self, request, *args, **kwargs)


class DetailView(generic.DetailView):
    model = Person
    template_name = 'phonebook/detail.html'

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')

        return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))


class PersonCreate(CreateView):
    model = Person
    fields = ['firstName', 'lastName']

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(PersonCreate, self).post(self, request, *args, **kwargs)


class PersonUpdate(UpdateView):
    model = Person
    fields = ['firstName', 'lastName']

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(PersonUpdate, self).post(self, request, *args, **kwargs)


class PersonDelete(DeleteView):
    model = Person
    success_url = reverse_lazy('phonebook:index')

    def delete(self, request, *args, **kwargs):
        try:
            self.get_object().delete()
        except ProtectedError:
            messages.add_message(request, messages.ERROR, 'Nie można usunąć osoby która posiada numer telefonu i/lub email!')
            return HttpResponseRedirect(self.success_url)
        return HttpResponseRedirect(self.success_url)


class PhoneCreate(CreateView):
    model = PhoneNumber
    fields = ['number']

    def form_valid(self, form):
        person = Person.objects.get(id=self.kwargs['pk'])
        form.instance.person = person
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(PhoneCreate, self).post(self, request, *args, **kwargs)


class PhoneUpdate(UpdateView):
    model = PhoneNumber
    fields = ['number']

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(PhoneUpdate, self).post(self, request, *args, **kwargs)


class PhoneDelete(DeleteView):
    model = PhoneNumber
    success_url = reverse_lazy('phonebook:index')


class EmailCreate(CreateView):
    model = Email
    fields = ['email']

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(EmailCreate, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        person = Person.objects.get(id=self.kwargs['pk'])
        form.instance.person = person
        return super().form_valid(form)


class EmailUpdate(UpdateView):
    model = Email
    fields = ['email']

    def post(self, request, *args, **kwargs):
        data = request.POST.get('data')
        if data:
            return HttpResponseRedirect(reverse('phonebook:search', kwargs={'data': data}))
        else:
            return super(EmailUpdate, self).post(self, request, *args, **kwargs)


class EmailDelete(DeleteView):
    model = Email
    success_url = reverse_lazy('phonebook:index')

website/phonebook/templates/phonebook/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'phonebook:index' %}">Książka telefoniczna</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'phonebook:add_person' %}">Dodaj osobę</a>
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Wyszukiwanie" value="{{ data }}" name="data" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Szukaj</button>
             </form>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

website/phonebook/templates/phonebook/detail.html
{% extends 'phonebook/base.html' %}
{% block title %}Dane osoby{% endblock %}

{% block body %}

<h3>{{ person }}</h3>
<h4>Numer:</h4>
<ul>
    {% for phone in person.phonenumber_set.all %}
        <li>{{ phone.number }}</li>
        <form action="{% url 'phonebook:delete_phone' phone.id person.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-trash"></span>
                </button>
        </form>
            <form action="{% url 'phonebook:update_phone' phone.id person.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-pencil"></span>
                </button>
            </form>
    {% endfor %}
    <br>
    <form action="{% url 'phonebook:add_phone' person.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-sm">
                    Dodaj numer telefonu
                </button>
    </form>
</ul>
<h4>Email:</h4>
<ul>
    {% for email in person.email_set.all %}
        <li>{{ email.email }}</li>
        <form action="{% url 'phonebook:delete_email' email.id person.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-trash"></span>
                </button>
        </form>
            <form action="{% url 'phonebook:update_email' email.id person.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-pencil"></span>
                </button>
            </form>
    {% endfor %}
    <br>
    <form action="{% url 'phonebook:add_email' person.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-sm">
                    Dodaj adres email
                </button>
    </form>
</ul>

{% endblock %}

website/phonebook/templates/phonebook/email_form.html
{% extends 'phonebook/base.html' %}
{% block title %}Dodaj osobę{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <br>
                        {% include 'phonebook/form-template.html' %}

                        <div class="form-group">


                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Dodaj</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/phonebook/templates/phonebook/form-template.html
{% for field in form %}

<div class="form-group row">

    <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>

{% endfor %}

website/phonebook/templates/phonebook/index.html
{% extends 'phonebook/base.html' %}
{% block title %}Książka telefoniczna{% endblock %}

{% block body %}
{% if all_people %}
    <ul>
        {% for person in all_people %}
        <li><a href="{% url 'phonebook:person_detail' person.id %}">{{ person }}</a>
            <form action="{% url 'phonebook:delete_person' person.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-trash"></span>
                </button>
            </form>
            <form action="{% url 'phonebook:update_person' person.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="fa fa-pencil"></span>
                </button>
            </form>
        </li>

        {% endfor %}
    </ul>
{% else %}
    <h4>Brak osób w książce!</h4>
{% endif %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{%endblock%}

website/phonebook/templates/phonebook/person_form.html
{% extends 'phonebook/base.html' %}
{% block title %}Dodaj osobę{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <br>
                        {% include 'phonebook/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Zatwierdź</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/phonebook/templates/phonebook/phonenumber_form.html
{% extends 'phonebook/base.html' %}
{% block title %}Dodaj osobę{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <br>
                        {% include 'phonebook/form-template.html' %}

                        <div class="form-group">


                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Dodaj</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/phonebook/templates/phonebook/searched.html
{% extends 'phonebook/base.html' %}
{% load classname %}
{% block title %}Wyniki wyszukiwania{% endblock %}

{% block body %}
<h3>Wyniki wyszukiwania:</h3>
{% if all_people %}
    <ul>
        {% for req in all_people %}
            {% with req|classname as modelclass %}
            {% if modelclass == "Person" %}
            <li><a href="{% url 'phonebook:person_detail' req.id %}">{{ req }}</a>
            </li>
            {% else %}
            <li><a href="{% url 'phonebook:person_detail' req.person_id %}">{{ req }}</a>
            </li>
            {% endif %}
            {% endwith %}

        {% endfor %}
    </ul>
{% else %}
    <h4>Brak danych!</h4>
{% endif %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{%endblock%}